import type { Metadata } from "next";
import { Newsreader, Inter, JetBrains_Mono } from "next/font/google";
import "./globals.css";
// import Provider from "./provider";
import Navbar from "./_components/navbar";

const newsreader = Newsreader({
  variable: "--font-newsreader",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const jetbrains_mono = JetBrains_Mono({
  variable: "--font-jetbrains-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Raji ラジ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${newsreader.variable} ${inter.variable} ${jetbrains_mono.variable} antialiased`}
      suppressHydrationWarning
    >
      <body className="grid grid-rows-[auto_1fr] bg-sand-50 selection:bg-sand-200 min-h-screen text-sand-900 [grid-template-area:'header'_'main'_'footer']">
        <Navbar />
        <div className="mt-(--header-height)">
          <div className="">{children}</div>
        </div>
      </body>
    </html>
  );
}
